import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
	docs: [
		'intro',
		'getting-started',
		{
			type: 'category',
			label: 'Concepts',
			collapsed: false,
			items: [{ type: 'autogenerated', dirName: 'concepts' }],
		},
		{
			type: 'category',
			label: 'Examples',
			collapsed: false,
			items: [{ type: 'autogenerated', dirName: 'examples' }],
		},
		{
			type: 'category',
			label: 'API Reference',
			collapsed: true,
			items: [{ type: 'autogenerated', dirName: 'api' }],
		},
	],
};

export default sidebars;
